### ISSUE TITLE
Can't search anything

### ISSUE THREAD

**Issue by VCTR18** [manuelvargastapia/libgen_mobile_app#18]
![Screenshot_20210116-141411_LibGen](https://user-images.githubusercontent.com/63024681/104818245-2e4fe200-5805-11eb-85cd-cffa67ff309f.jpg)
This happens every time I try to search something, and the web page is up, I checked that.
It says "Something went wrong, please try later".

**Comment by manuelvargastapia** [comment]
Thanks for reporting this issue. It seems a problem with the backend. I restart it and now it should be working

**Comment by VCTR18** [comment]
Yeah, it works now. Thanks.
