### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by Rosarywin12** [manuelvargastapia/libgen_mobile_app#25]
"Ups! We messed it up". Same thing on my devices, reinstall and all.

**Comment by manuelvargastapia** [comment]
Hi. I'm so sorry for this. The backend service will be down for a few days. I miscalculate the resource consumption of my projects and today I reach the limit.

The service will be available again next month. I'm sorry.

**Comment by manuelvargastapia** [comment]
Hi @Rosarywin12. The app is working again. Again, I'm sorry for this. I'll make sure this won't happen again. Best regards.
