### ISSUE TITLE
"#" not allowed in search

### ISSUE THREAD

**Issue by alonsobustamante98** [manuelvargastapia/libgen_mobile_app#26]
This is really short.
I searched for "C# in a nutshell" and it showed no search results, returning the "Ups!" message. Searching for "in a nutshell ", does. After some fiddling it seems the "#" is at fault.

**Comment by manuelvargastapia** [comment]
Thanks for pointing this. You're right. I'll fix this in the next release (I don't know how long it'll take, I'm sorry)

**Comment by manuelvargastapia** [comment]
This issue is fixed in the new version 1.1.0
