### ISSUE TITLE
Feature: Black theme

### ISSUE THREAD

**Issue by Atrate** [manuelvargastapia/libgen_mobile_app#5]
Including a black theme, in addition to the light and dark themes, can help improve battery life on AMOLED displays.

On such displays, a #000000 background would decrease energy consumption significantly, as AMOLED screens do not "display" black as LCD screens do.

**Comment by manuelvargastapia** [comment]
Thanks for the advice. Honestly, I wasn't aware of the different screens available and their effects on energy consumption. I did a little research, and now I get it.

Indeed, it seems a desirable feature. However, the app is not intended to be used for large periods. So, I don't see a truly significant improvement in battery consumption for now.
